apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorite-auth-svc
  namespace: explorite
spec:
  selector:
    matchLabels:
      app: auth_service
  template:
    metadata:
      labels:
        app: auth_service
    spec:
      containers:
        - image: ananyaep90/auth-svc:2.2
          name: auth-svc-container
          ports:
            - containerPort: 8001
          resources:
            limits:
              memory: 212Mi
              cpu: ".2"
            requests:
              memory: 150Mi
              cpu: "0.1"


---
apiVersion: v1
kind: Service
metadata:
  name: auth-services
  namespace: explorite
spec: 
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8001
  selector:
    app: auth_service
