apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorite-chat-svc
  namespace: explorite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server_service
  template:
    metadata:
      labels:
        app: server_service
    spec:
      containers:
        - name: chat-svc-container
          image: ananyaep90/chat-svc:2.2
          ports:
          -  containerPort: 8003
          resources:
            limits:
              memory: 212Mi
              cpu: ".2"
            requests:
              memory: 150Mi
              cpu: "0.1"

---

apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: explorite
spec: 
  type: ClusterIP
  ports:
    - port: 50054
      targetPort: 50054
  selector:
    app: chat_service
