apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorite-post-svc
  namespace: explorite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: friend_service
  template:
    metadata:
      labels: 
        app: friend_service
    spec:
      containers:
      - image: ananyaep90/post-svc
        name: post-svc-container
        ports:
        - containerPort: 8002
        resources:
          limits:
            cpu: ".2"
            memory: "250Mi"
          requests:
            cpu: ".1"
            memory: "150Mi"
        

---

apiVersion: v1
kind: Service
metadata:
  namespace: explorite
  name: post-service
spec:
  type: ClusterIP
  ports:
  - port: 8002
    targetPort: 8002
  selector:
    app: post_service