apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorite-post-svc
  namespace: explorite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post_service
  template:
    metadata:
      labels: 
        app: post_service
    spec:
      containers:
      - image: ananyaep90/post-svc:3.3
        name: post-svc-container
        ports:
        - containerPort: 50051
        resources:
          limits:
            cpu: ".2"
            memory: "250Mi"
          requests:
            cpu: ".1"
            memory: "150Mi"
        

---

apiVersion: v1
kind: Service
metadata:
  namespace: explorite
  name: post-service
spec:
  type: ClusterIP
  ports:
  - port: 50051
    targetPort: 50051
  selector:
    app: post_service